### ISSUE TITLE
Music Streaming

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot2.0#4]

**Comment by SteamingMutt** [comment]
There exists a NPM module called DiscordDJ (I think) that'll simplify the implementation progress of this.

**Comment by Perpetucake** [comment]
We will make this happen.

**Comment by Guichaguri** [comment]
Hello, I'm the developer of DiscordDJ, the project is still WIP, that's why I want to ask a simple question: What do you expect from the API? This way I can make a better API

**Comment by SteamingMutt** [comment]
We expect the API to at least have basic playback support, playlists, skipping and requesting.
