### ISSUE TITLE
Auth levels per server

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot2.0#8]
Upon joining a server, the bot makes the founder of the server a level 3 user unique to that server, this way server owners can independently decide who should use what commands.   

Auth levels per command are set by the script and can't be adjusted via conventional ways.    

This requires the use of Redis, MySQL or any other database though.

**Comment by SteamingMutt** [comment]
#2 needs to be finished before this can begin.

**Comment by Perpetucake** [comment]
We need databases QQ

**Comment by SteamingMutt** [comment]
I vote for using Redis, it's comparatively easier than SQL
https://www.npmjs.com/package/redis
