### ISSUE TITLE
NSFW toggle flag unique to channels

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot2.0#9]
If we are going to include commands that can potentially be NSFW, it's better to make a command that can toggle those commands on and off for use in a specific channel.

This also requires a database, like Redis.

**Comment by Perpetucake** [comment]
Selecting a database solution will make life way better. I know little about sql and nothing about Redis though. Whatever we decide on will also be used to store !trivia user data, the main hindrance at the moment.

**Comment by SteamingMutt** [comment]
Doesn't seem to function correctly.
